### ISSUE TITLE
BRF additions

### ISSUE THREAD

**Issue by cukiemunster** [BadBoy-Ultimate-Raider/BadBoy#114]
This is going to be a support thread for Blackrock Foundry, and anything relating to it that may cause problems with BB.

**Comment by cukiemunster** [comment]
http://www.wowhead.com/spell=160838/disrupting-roar is going to need to be added into BB core to stop casting. This is for Hans'gar and Franzok fight, Franzok specificly does this cast

**Comment by cukiemunster** [comment]
Also, Chumii mentioned that he thought BB still only checked for boss1 when there are multiple bosses, not sure what the situation is on this, but it will need to be resolved ASAP if so, since BRF has quite a few multi boss encounters.

**Comment by modhunter** [comment]
During the Kromog encounter, there is a mechanic where a bunch of stone 'hands' will spawn on the ground. Players need to 'stand' in the hands and they will 'grab' the player, preventing them from moving. The hands are units that must be DPSed down. You can DPS the hand holding you. I think this is very similar to the mechanic in the skyreach encounter where the bid thing flys you off the platform.  While you're being held, the BB rotation will stop working.

The 'debuff' cast on you (I think it's cast on you) is spellID 157059 or 157060 - not sure. The 'hand' holding you is unitID 77893 and/or 77891.

I'm pretty confident that the issue preventing the rotation from executing is either because the player is considered to be IsMounted() or UnitInVehicle()

**Comment by modhunter** [comment]
After watching videos of the encounter, the player is definitely getting a buff or debuff when grasped by the hand.  It's spellID 157059 or 157060.

**Comment by averykey** [comment]
ive added the ids into the mount code, lets see if that fixes your problem. ive also added the http://www.wowhead.com/spell=160838/disrupting-roar id into our stop casting method.

**Comment by modhunter** [comment]
I think all references of “UnitInVehicle("Player")” need to be changed to “UnitHasVehicleUI(“Player")”

**Comment by popster** [comment]
modhunter what cast method is your profile using? mine (Fury Warrior) didn't cast AT ALL on kromag

**Comment by modhunter** [comment]
I think you don't cast at all in your Fury Warrior rotation because of this on line 71 in Rotations/Warrior/Fury/Fury.lua:

    if canRun() ~= true or UnitInVehicle("Player") then
      return false;
    end

**Comment by popster** [comment]
Anyone else have a good kromag with badboy? Mine still wouldn't cast =/
