### ISSUE TITLE
Brewmaster 

### ISSUE THREAD

**Issue by Moonst** [BadBoy-Ultimate-Raider/BadBoy#131]
Hey chumii i love the new set up although finding i love gaurd on cd helps with survival and aoe works great not much else i can say lmao its working beautifully but yeah gaurd on cd i think is much better

**Comment by Moonst** [comment]
oh and the aoe is working awesome

**Comment by chumiiger** [comment]
I got raid tonight and will test guard then, will see how I like it. maybe I will do multiple options for it like "On CD" and "Simc way" or sth, will see
Touch of Death doesnt look for bosses or sth, but sure I could do that, maybe isBoss and a table for specific mobs (like Kromog hands).
Kromog hands is a badboy issue, not rotation issue. it has sth to do with mounts / vehicles. we still need to figure it out i think, just adding it to the "ignore LoS" list didnt seem to help

**Comment by Moonst** [comment]
gotcha and yeah toggle for different occasions would be great for gaurd or make it so your always pooling 2 chi when using ascension or save one charge of chi brew so you can use the one gaurd that is saved when needed. great work man your awsome

**Comment by chumiiger** [comment]
so i tried it tonight on furnace heroic and i must say, i like the way guard is right now. you can always spam you guard key if you really need it, but i think i will make an option for it anyways. I always wanted to add some "boss related guard usage", meaning to always save 1 guard for a specific boss ability, take the breath on brakenspore for example. maybe i will have a look at that project again too.

stagger is the most advanced logic i can do, you sure you were at high stagger and had 1 chi to purify? it should work like this: if at high stagger, use chi immediatly to purify, if at medium stagger and stagger would damage you for 25% + of your health if not cleared, then purify. if at light stagger, ignore it. I could maybe add an option if you want to purify medium at lower health % value, but 25 was fine since MoP. I never had any issues sitting on high stagger too long, I am using tiger strikes instead of chi brew/ascension tho..

**Comment by Moonst** [comment]
kk yeah i tanked kromog heroic tonight and yeah it seems to be really nice and it may have been me but yeah it was clearing stagger fine and i got my 2 set so i wont have as much energy prob i think that's where i was having trouble but yeah pretty solid and yeah i like ascention as well more energy means more mitigation ill give powerful strikes a try see how that goes but thank you is working great
