### ISSUE TITLE
Anyone banned?

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#154]
heard mini-banwave went out to some FH users, but I'm still standing.. you guys okay?

**Comment by Kiwical** [comment]
Not yet lol but probably incoming.

**Comment by popster** [comment]
Yeah I hope you keep your account, I think we might have dodged it for whatever reason.

How hard would it be to open BadBoy to other LUA unlockers so users can choose their preferred and most trusted one? FireHack has gotten so much heat recently, and I'd prefer to use something like like oLUA from now on, but the BadBoy engine is so good I don't want to give it up. :(

**Comment by Kiwical** [comment]
Yeah im starting to think the people who are getting banned are using scripts for PvP, blizzard have a hard on for PvP botting atm because of all the outrage of the past WoD Season maybe its last banwave before 6.2 and Season 2 of pvp, and i also mentioned in FH forums the last few weeks new forum posters have been coming in and asking for custom made pvp interrupt scripts and are willing to pay for it.

**Comment by popster** [comment]
Yeah this wouldn't surprise me if this was aimed at people detected using LUA scripts in PvP combat, maybe they're going to leave us PvEers alone :D

**Comment by Kiwical** [comment]
All i know is when i wake up tomorrow im either banned or im not if im not that means either its something probably the extra features within FH thats been detected and if im banned its probably FH regardless of the functions and probably a rotation script, PE i havent used in months badboy i used twice this week once when the paladin error came up and the 2nd time to do my harrison jones daily and thats it, other times its Soap Rotations.

**Comment by Defmaster** [comment]
Yeah thats one reason why we dont support using the addon in pvp. Its for use in pve where you do no harm. Pvp is about competion against other player ,  and it should stay that way. PvE is about killing a boss over and over again, without any unexcpected events. 
Fh is used over other unlocker because it supports more features, the object manager is one thats heavenly used. Because of that manager automatic AoE is Wirkung great. No comparison to PE :-) 
For sure some could write a pvp profile, but it will not be implemented into master branch.
But like for all things: use it at your own risk

**Comment by popster** [comment]
It looks like the bans mainly went to users or former users of PE / ccR... strictly BB users seem safe :D I'm pretty sure the wave was addon based, how else would some FH users get banned, and some not...

**Comment by Kiwical** [comment]
Phew lol well my account is still save woke up and no ban i did use PE but i havent used it in ages, never used ccR

**Comment by popster** [comment]
any other LUA breakers out there with object manager? I know shitbox rotations has one (for those who don't know soapbox rotations works as a fully functional LUA breaker, you don't have to use the rotations they provide to execute protected functions), but object API not public, can anyone get it somehow?

**Comment by Kiwical** [comment]
I highly doubt they will give that out to anyone but themselves as they are making money from it.

**Comment by popster** [comment]
yeah they definitely won't, but there's a cracked version of it, I asked the guy who cracked it if he could hook me up with the source files (don't even know if he has them), we'll see

**Comment by popster** [comment]
Got the source .lua and all the functions, it's basically firehack and the object manager is written by the same person, so if there's any risk with firehack it's the same with soapbox lol

anyway, here's the source.lua:
https://www.dropbox.com/s/zdcp2dqb4j8ifbl/6-17-2015_32.lua

it's pretty interesting for looking at some advanced functions and whatnot, good file to have on hand

**Comment by popster** [comment]
o okay sry

**Comment by ragnarger** [comment]
post your skype ID, so we can talk
i will add you and delete it here.

**Comment by popster** [comment]
sure, it's kamronskypes

**Comment by Kiwical** [comment]
I think his free rotations are pretty good, though $30 is way over the top its double a sub fee i could see myself buying a couple of profiles if it comes down to it, but not all of them i cant stand having to many alts  one of the guild members uses soaps  holy paladin profile and he doesn't do to bad during Heroic BRF fights.

**Comment by Kiwical** [comment]
So anyone heard anything about any update for FH yet.

**Comment by popster** [comment]
dunno but feel free to add me on skype if u want to know how to use soapbox as FH (you can even use the free trial version)

**Comment by popster** [comment]
my skype is kamronskypes

**Comment by Kiwical** [comment]
Are you meaning Soaps 1-99 free rotations i have that but nothing for 100

**Comment by Kiwical** [comment]
FH could be back by the weekend lets hope.
