### ISSUE TITLE
DPS monk some small bug

### ISSUE THREAD

**Issue by leaderquebec** [BadBoy-Ultimate-Raider/BadBoy#194]
1: when i target some one if my target is out off range wow and fh crash if badboy is (On) 

2: some time in fight monk stop working for aprox 10 - 15 sec. i click on any spell in my barr and they began to run

**Comment by CuteOne** [comment]
1: That is a weird issue, I will see if I can't duplicate

2: This is likely due to lack of chi and the profiles strict adherence to maintaining the combo buff (where it is maintained so long as you don't repeat the last used spell) I will see what I can do to solve this without causing the loss of this buff, else I will just have it use Tiger Palm again.

**Comment by CuteOne** [comment]
I fixed the issue with the profile stopping but this could cause Hit Combo buff to be reset...better than not working though. 

As far as crashing when targeting out of range, I have not been able to reproduce this.

**Comment by leaderquebec** [comment]
For the crash prob my video card idk not sure but anyway thank you for ur time on this 👍
